import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const BLOG_DIR = path.join(ROOT, "content", "blog");
const PILLAR_DIR = path.join(ROOT, "content", "pillars");
const OUT_FILE = path.join(ROOT, "generated", "content-manifest.ts");

function readJsonDir(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith(".json"))
    .map((name) => {
      const filePath = path.join(dir, name);
      const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
      return { filePath, data };
    });
}

function validateBlog(post) {
  const required = [
    "slug",
    "pillar",
    "publishedAt",
    "updatedAt",
    "seo",
    "headline",
    "intro",
    "tags",
    "sections",
    "faq",
  ];
  for (const key of required) {
    if (post[key] === undefined) {
      throw new Error(`Blog post "${post.slug}" missing required field: ${key}`);
    }
  }
  if (!post.seo?.title || !post.seo?.description || !post.seo?.canonical) {
    throw new Error(`Blog post "${post.slug}" missing seo.title, description, or canonical`);
  }
}

function validatePillar(pillar) {
  const required = [
    "slug",
    "publishedAt",
    "updatedAt",
    "seo",
    "headline",
    "intro",
    "sections",
    "faq",
  ];
  for (const key of required) {
    if (pillar[key] === undefined) {
      throw new Error(`Pillar "${pillar.slug}" missing required field: ${key}`);
    }
  }
}

function tagOverlap(a, b) {
  const setB = new Set(b);
  return a.filter((tag) => setB.has(tag)).length;
}

function keywordOverlap(a, b) {
  const setB = new Set((b ?? []).map((k) => k.toLowerCase()));
  return (a ?? []).filter((k) => setB.has(k.toLowerCase())).length;
}

function computeRelatedPosts(post, allPosts) {
  const scores = allPosts
    .filter((other) => other.slug !== post.slug)
    .map((other) => {
      let score = 0;
      if (other.pillar === post.pillar) score += 3;
      score += tagOverlap(post.tags ?? [], other.tags ?? []);
      score += keywordOverlap(post.seo?.keywords ?? [], other.seo?.keywords ?? []);
      return { slug: other.slug, score };
    })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score);

  return scores.slice(0, 4).map(({ slug }) => slug);
}

function serializeManifest({ blogIndex, pillarIndex, blogBySlug, pillarBySlug }) {
  const payload = {
    generatedAt: new Date().toISOString(),
    blogIndex,
    pillarIndex,
    blogBySlug,
    pillarBySlug,
  };

  return `/* eslint-disable */
// Auto-generated by scripts/generate-blog.mjs — do not edit manually.
export const CONTENT_MANIFEST_GENERATED_AT = ${JSON.stringify(payload.generatedAt)};

export const BLOG_INDEX = ${JSON.stringify(blogIndex, null, 2)} as const;

export const PILLAR_INDEX = ${JSON.stringify(pillarIndex, null, 2)} as const;

export const BLOG_BY_SLUG = ${JSON.stringify(blogBySlug, null, 2)} as const;

export const PILLAR_BY_SLUG = ${JSON.stringify(pillarBySlug, null, 2)} as const;
`;
}

function main() {
  const pillars = readJsonDir(PILLAR_DIR).map(({ data }) => data);
  const posts = readJsonDir(BLOG_DIR).map(({ data }) => data);

  pillars.forEach(validatePillar);
  posts.forEach(validateBlog);

  const pillarSlugs = new Set(pillars.map((p) => p.slug));
  for (const post of posts) {
    if (!pillarSlugs.has(post.pillar)) {
      throw new Error(
        `Blog post "${post.slug}" references unknown pillar "${post.pillar}"`
      );
    }
  }

  const blogBySlug = {};
  for (const post of posts) {
    const relatedPostSlugs = computeRelatedPosts(post, posts);
    blogBySlug[post.slug] = {
      slug: post.slug,
      path: `/blog/${post.slug}`,
      pillar: post.pillar,
      headline: post.headline,
      intro: post.intro,
      publishedAt: post.publishedAt,
      updatedAt: post.updatedAt,
      seo: post.seo,
      tags: post.tags,
      relatedPostSlugs,
    };
  }

  const pillarBySlug = {};
  for (const pillar of pillars) {
    const blogSlugs = posts
      .filter((post) => post.pillar === pillar.slug)
      .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt))
      .map((post) => post.slug);

    pillarBySlug[pillar.slug] = {
      slug: pillar.slug,
      path: `/topics/${pillar.slug}`,
      headline: pillar.headline,
      intro: pillar.intro,
      publishedAt: pillar.publishedAt,
      updatedAt: pillar.updatedAt,
      seo: pillar.seo,
      blogSlugs,
    };
  }

  const blogIndex = Object.values(blogBySlug).sort((a, b) =>
    b.publishedAt.localeCompare(a.publishedAt)
  );
  const pillarIndex = Object.values(pillarBySlug);

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(
    OUT_FILE,
    serializeManifest({ blogIndex, pillarIndex, blogBySlug, pillarBySlug })
  );

  const contentUrls = [
    "/blog",
    ...blogIndex.map((entry) => entry.path),
    ...pillarIndex.map((entry) => entry.path),
  ];
  fs.writeFileSync(
    path.join(ROOT, "generated", "content-urls.json"),
    JSON.stringify(contentUrls, null, 2)
  );

  console.log(
    `Generated content manifest: ${posts.length} blog posts, ${pillars.length} pillars`
  );
}

main();
